version: '3.9'

services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: compliance_backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - compliance-net
    command: sh -c "npm run build && npm run dev"

  frontend:
    build: ./frontend
    container_name: compliance_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - compliance-net

networks:
  compliance-net:
    driver: bridge
