version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: compliance-dash-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - OPENAI_API_KEY=${OPENAI_API_KEY:-demo_key}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-demo}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-demo}
    networks:
      - compliance-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z 127.0.0.1 4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: compliance-dash-frontend
    ports:
      - "3002:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - compliance-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  compliance-network:
    driver: bridge